-- Creación de tablas
CREATE TABLE
    ADMINISTRADOR (
        ID SERIAL,
        NOMBRE VARCHAR(15) UNIQUE NOT NULL,
        CLAVE VARCHAR(25) NOT NULL,
        CORREO VARCHAR(25) NOT NULL,
        PRIMARY KEY (ID)
    );

CREATE TABLE
    ASESORES (
        DNI VARCHAR(8) NOT NULL,
        NOMBRE VARCHAR(25) NOT NULL,
        CLAVE VARCHAR(25) NOT NULL,
        PRIMARY KEY (DNI)
    );

CREATE TABLE
    SUPERVISORES (
        DNI VARCHAR(8) NOT NULL,
        NOMBRE VARCHAR(25) NOT NULL,
        CLAVE VARCHAR(25) NOT NULL,
        PRIMARY KEY (DNI)
    );

CREATE TABLE
    PACIENTES (
        DNI VARCHAR(8) NOT NULL,
        NOMBRE VARCHAR(25) NOT NULL,
        PRIMARY KEY (DNI)
    );

CREATE TABLE
    EXAMENES (
        ID SERIAL,
        NOMBRE VARCHAR(25) NOT NULL,
        COSTO DECIMAL(10, 2) NOT NULL,
        PRIMARY KEY (ID)
    );

CREATE TABLE
    PEDIDOS (
        ID SERIAL,
        ID_ASESOR VARCHAR(8) NOT NULL,
        ID_PACIENTE VARCHAR(8) NOT NULL,
        CANTIDAD INT,
        FECHA DATE NOT NULL,
        PRIMARY KEY (ID)
    );

CREATE TABLE
    DETALLES (
        ID_PEDIDO INT NOT NULL,
        ID_EXAMEN INT NOT NULL,
        RESULTADO VARCHAR(25),
        COMENTARIO VARCHAR(50),
        PRIMARY KEY (ID_PEDIDO, ID_EXAMEN)
    );

CREATE TABLE
    ATENCIONES (
        ID SERIAL,
        ID_ASESOR VARCHAR(8) NOT NULL,
        ID_SUPERVISOR VARCHAR(8) NOT NULL,
        PRIMARY KEY (ID)
    );

-- Filtros
ALTER TABLE ATENCIONES ADD CONSTRAINT atencion_ibfk_1 FOREIGN KEY (ID_ASESOR) REFERENCES ASESORES (DNI),
ADD CONSTRAINT atencion_ibfk_2 FOREIGN KEY (ID_SUPERVISOR) REFERENCES SUPERVISORES (DNI);

ALTER TABLE PEDIDOS ADD CONSTRAINT pedido_ibfk_1 FOREIGN KEY (ID_ASESOR) REFERENCES ASESORES (DNI),
ADD CONSTRAINT pedido_ibfk_2 FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES (DNI);

ALTER TABLE DETALLES ADD CONSTRAINT detalle_ibfk_1 FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS (ID),
ADD CONSTRAINT detalle_ibfk_2 FOREIGN KEY (ID_EXAMEN) REFERENCES EXAMENES (ID);