-- Creación de tablas
CREATE TABLE
    ADMINISTRADORES (
        ID SMALLINT AUTO_INCREMENT NOT NULL,
        USUARIO VARCHAR(15) UNIQUE NOT NULL,
        CLAVE VARCHAR(25) NOT NULL,
        CORREO VARCHAR(25) NOT NULL,
        PRIMARY KEY (ID)
    );

CREATE TABLE
    ASESORES (
        DNI VARCHAR(8) NOT NULL,
        CLAVE VARCHAR(25) NOT NULL,
        NOMBRES VARCHAR(25) NOT NULL,
        APELLIDOS VARCHAR(60) NOT NULL,
        TELEFONO VARCHAR(9),
        CORREO VARCHAR(25),
        FECHA_NACIMIENTO DATE,
        ESTADO BOOLEAN,
        PRIMARY KEY (DNI)
    );

CREATE TABLE
    SUPERVISORES (
        DNI VARCHAR(8) NOT NULL,
        CLAVE VARCHAR(25) NOT NULL,
        NOMBRES VARCHAR(25) NOT NULL,
        APELLIDOS VARCHAR(60) NOT NULL,
        TELEFONO VARCHAR(9),
        CORREO VARCHAR(25),
        FECHA_NACIMIENTO DATE,
        ESTADO BOOLEAN,
        PRIMARY KEY (DNI)
    );

CREATE TABLE
    PACIENTES (
        DNI VARCHAR(8) NOT NULL,
        NOMBRES VARCHAR(25) NOT NULL,
        APELLIDOS VARCHAR(60) NOT NULL,
        DIRECCION VARCHAR(30),
        TELEFONO VARCHAR(9),
        CORREO VARCHAR(25),
        FECHA_NACIMIENTO DATE,
        PRIMARY KEY (DNI)
    );

CREATE TABLE
    EXAMENES_MEDICOS (
        ID SMALLINT AUTO_INCREMENT NOT NULL,
        NOMBRE VARCHAR(25) NOT NULL,
        COSTO DECIMAL(10, 2) NOT NULL,
        STOCK SMALLINT,
        PRIMARY KEY (ID)
    );

CREATE TABLE
    ATENCIONES (
        ID SMALLINT AUTO_INCREMENT NOT NULL,
        ID_PACIENTE VARCHAR(8) NOT NULL,
        ID_ASESOR VARCHAR(8) NOT NULL,
        ID_CAMPANA SMALLINT NOT NULL,
        CANTIDAD_TIRAS SMALLINT NOT NULL,
        FECHA_ATENCION DATE NOT NULL,
        PRIMARY KEY (ID)
    );

CREATE TABLE
    ATENCIONES_EXAMENES (
        ID_ATENCION SMALLINT NOT NULL,
        ID_EXAMEN SMALLINT NOT NULL,
        RESULTADO VARCHAR(25),
        COMENTARIO VARCHAR(50),
        PRIMARY KEY (ID_ATENCION, ID_EXAMEN)
    );

CREATE TABLE
    CAMPANAS_MEDICAS (
        ID SMALLINT AUTO_INCREMENT NOT NULL,
        ID_SUPERVISOR VARCHAR(8) NOT NULL,
        UBICACION VARCHAR(35) NOT NULL,
        HORARIO VARCHAR(25) NOT NULL,
        PRIMARY KEY (ID)
    );

-- Filtros
ALTER TABLE CAMPANAS_MEDICAS ADD CONSTRAINT CAMPANAS_MEDICAS_ibfk_1 FOREIGN KEY (ID_SUPERVISOR) REFERENCES SUPERVISORES (DNI);

ALTER TABLE ATENCIONES 
ADD CONSTRAINT ATENCIONES_ibfk_1 FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES (DNI),
ADD CONSTRAINT ATENCIONES_ibfk_2 FOREIGN KEY (ID_ASESOR) REFERENCES ASESORES (DNI),
ADD CONSTRAINT ATENCIONES_ibfk_3 FOREIGN KEY (ID_CAMPANA) REFERENCES CAMPANAS_MEDICAS (ID);

ALTER TABLE ATENCIONES_EXAMENES 
ADD CONSTRAINT ATENCIONES_EXAMENES_ibfk_1 FOREIGN KEY (ID_ATENCION) REFERENCES ATENCIONES (ID),
ADD CONSTRAINT ATENCIONES_EXAMENES_ibfk_2 FOREIGN KEY (ID_EXAMEN) REFERENCES EXAMENES_MEDICOS (ID);